ARG HA_VERSION=2025.12.5

# Stage 1: Use the local image as base
FROM home-assistant-arm64-slim:${HA_VERSION} AS base

# Remove unnecessary packages
RUN <<EOF
uv pip remove AEMET-OpenData
uv pip remove AIOSomecomfort
uv pip remove Adax-local
uv pip remove DoorBirdPy
uv pip remove HAP-python
uv pip remove HATasmota
uv pip remove HueBLE
uv pip remove Mastodon.py
uv pip remove PSNAWP
uv pip remove Pillow
uv pip remove PlexAPI
uv pip remove ProgettiHWSW
uv pip remove PyChromecast
uv pip remove PyFlume
uv pip remove PyFronius
uv pip remove PyLoadAPI
uv pip remove PyMetEireann
uv pip remove PyMetno
uv pip remove PyMicroBot
uv pip remove PyNaCl
uv pip remove PyQRCode
uv pip remove PyRMVtransport
uv pip remove PySrDaliGateway
uv pip remove PySwitchbot
uv pip remove PySwitchmate
uv pip remove PySyncThru
uv pip remove PyTransportNSW
uv pip remove PyTurboJPEG
uv pip remove PyViCare
uv pip remove PyXiaomiGateway
uv pip remove RachioPy
uv pip remove RestrictedPython
uv pip remove RtmAPI
uv pip remove SQLAlchemy
uv pip remove Tami4EdgeAPI
uv pip remove TravisPy
uv pip remove TwitterAPI
uv pip remove WSDiscovery
uv pip remove accuweather
uv pip remove actron-neo-api
uv pip remove adax
uv pip remove adb-shell[async]
uv pip remove adext
uv pip remove adguardhome
uv pip remove advantage-air
uv pip remove afsapi
uv pip remove agent-py
uv pip remove aio-geojson-generic-client
uv pip remove aio-geojson-geonetnz-quakes
uv pip remove aio-geojson-geonetnz-volcano
uv pip remove aio-geojson-nsw-rfs-incidents
uv pip remove aio-geojson-usgs-earthquakes
uv pip remove aio-georss-gdacs
uv pip remove aio-ownet
uv pip remove aioacaia
uv pip remove aioairq
uv pip remove aioairzone-cloud
uv pip remove aioairzone
uv pip remove aioamazondevices
uv pip remove aioambient
uv pip remove aioapcaccess
uv pip remove aioaquacell
uv pip remove aioaseko
uv pip remove aioasuswrt
uv pip remove aioautomower
uv pip remove aioazuredevops
uv pip remove aiobafi6
uv pip remove aiobotocore
uv pip remove aiocomelit
uv pip remove aiodhcpwatcher
uv pip remove aiodiscover
uv pip remove aiodns
uv pip remove aiodukeenergy
uv pip remove aioeafm
uv pip remove aioeagle
uv pip remove aioecowitt
uv pip remove aioelectricitymaps
uv pip remove aioemonitor
uv pip remove aioesphomeapi
uv pip remove aiofiles
uv pip remove aioflo
uv pip remove aioftp
uv pip remove aiogithubapi
uv pip remove aioguardian
uv pip remove aioharmony
uv pip remove aiohasupervisor
uv pip remove aiohomeconnect
uv pip remove aiohomekit
uv pip remove aiohttp_sse
uv pip remove aiohue
uv pip remove aioimaplib
uv pip remove aioimmich
uv pip remove aiokafka
uv pip remove aiokef
uv pip remove aiokem
uv pip remove aiolifx-effects
uv pip remove aiolifx-themes
uv pip remove aiolifx
uv pip remove aiolookin
uv pip remove aiolyric
uv pip remove aiomealie
uv pip remove aiomodernforms
uv pip remove aiomusiccast
uv pip remove aionanoleaf
uv pip remove aionotion
uv pip remove aiontfy
uv pip remove aionut
uv pip remove aioonkyo
uv pip remove aioopenexchangerates
uv pip remove aiooui
uv pip remove aiopegelonline
uv pip remove aiopulse
uv pip remove aiopurpleair
uv pip remove aiopvapi
uv pip remove aiopvpc
uv pip remove aiopyarr
uv pip remove aioqsw
uv pip remove aioraven
uv pip remove aiorecollect
uv pip remove aioridwell
uv pip remove aioruckus
uv pip remove aiorussound
uv pip remove aioruuvigateway
uv pip remove aiosenz
uv pip remove aioshelly
uv pip remove aioskybell
uv pip remove aioslimproto
uv pip remove aiosolaredge
uv pip remove aiosteamist
uv pip remove aiostreammagic
uv pip remove aioswitcher
uv pip remove aiosyncthing
uv pip remove aiotankerkoenig
uv pip remove aiotedee
uv pip remove aiotractive
uv pip remove aiounifi
uv pip remove aiousbwatcher
uv pip remove aiovlc
uv pip remove aiovodafone
uv pip remove aiowaqi
uv pip remove aiowatttime
uv pip remove aiowebdav2
uv pip remove aiowebostv
uv pip remove aiowithings
uv pip remove aioymaps
uv pip remove airgradient
uv pip remove airly
uv pip remove airos
uv pip remove airthings-ble
uv pip remove airthings-cloud
uv pip remove airtouch4pyapi
uv pip remove airtouch5py
uv pip remove alpha-vantage
uv pip remove altruistclient
uv pip remove amberelectric
uv pip remove amcrest
uv pip remove androidtv[async]
uv pip remove androidtvremote2
uv pip remove anel-pwrctrl-homeassistant
uv pip remove anova-wifi
uv pip remove anthemav
uv pip remove anthropic
uv pip remove anyio
uv pip remove apple_weatherkit
uv pip remove apprise
uv pip remove aprslib
uv pip remove apsystems-ez1
uv pip remove aqualogic
uv pip remove aranet4
uv pip remove arcam-fmj
uv pip remove arris-tg2492lg
uv pip remove asmog
uv pip remove asusrouter
uv pip remove async-upnp-client
uv pip remove asyncarve
uv pip remove asyncinotify
uv pip remove asyncpysupla
uv pip remove asyncsleepiq
uv pip remove asyncssh
uv pip remove # atenpdu
uv pip remove auroranoaa
uv pip remove aurorapy
uv pip remove autarco
uv pip remove automower-ble
uv pip remove av
uv pip remove avea
uv pip remove # avion
uv pip remove axis
uv pip remove ayla-iot-unofficial
uv pip remove azure-eventhub
uv pip remove azure-kusto-data[aio]
uv pip remove azure-kusto-ingest
uv pip remove azure-servicebus
uv pip remove azure-storage-blob
uv pip remove b2sdk
uv pip remove babel
uv pip remove baidu-aip
uv pip remove base36
uv pip remove batinfo
uv pip remove beautifulsoup4
uv pip remove # beewi-smartclim
uv pip remove bimmer-connected[china]
uv pip remove bizkaibus
uv pip remove bleak-esphome
uv pip remove bleak-retry-connector
uv pip remove bleak
uv pip remove blebox-uniapi
uv pip remove blinkpy
uv pip remove blockchain
uv pip remove bluecurrent-api
uv pip remove bluemaestro-ble
uv pip remove bluetooth-adapters
uv pip remove bluetooth-auto-recovery
uv pip remove bluetooth-data-tools
uv pip remove bond-async
uv pip remove bosch-alarm-mode2
uv pip remove boschshcpy
uv pip remove boto3
uv pip remove botocore
uv pip remove bring-api
uv pip remove broadlink
uv pip remove brother
uv pip remove brottsplatskartan
uv pip remove brunt
uv pip remove bthome-ble
uv pip remove bthomehub5-devicelist
uv pip remove btsmarthub-devicelist
uv pip remove buienradar
uv pip remove cached-ipaddress
uv pip remove caldav
uv pip remove ciscomobilityexpress
uv pip remove clearpasspy
uv pip remove clx-sdk-xms
uv pip remove coinbase-advanced-py
uv pip remove colorlog
uv pip remove colorthief
uv pip remove compit-inext-api
uv pip remove concord232
uv pip remove connect-box
uv pip remove construct
uv pip remove cookidoo-api
uv pip remove cronsim
uv pip remove crownstone-cloud
uv pip remove crownstone-sse
uv pip remove crownstone-uart
uv pip remove datadog
uv pip remove datapoint
uv pip remove dbus-fast
uv pip remove debugpy
uv pip remove decora-wifi
uv pip remove deebot-client
uv pip remove defusedxml
uv pip remove deluge-client
uv pip remove demetriek
uv pip remove denonavr
uv pip remove devialet
uv pip remove devolo-home-control-api
uv pip remove devolo-plc-api
uv pip remove dio-chacon-wifi-api
uv pip remove directv
uv pip remove discogs-client
uv pip remove discovery30303
uv pip remove dremel3dpy
uv pip remove dropmqttapi
uv pip remove dsmr-parser
uv pip remove dwdwfsapi
uv pip remove dynalite-devices
uv pip remove dynalite-panel
uv pip remove eagle100
uv pip remove easyenergy
uv pip remove ebusdpy
uv pip remove ecoaliface
uv pip remove eheimdigital
uv pip remove ekey-bionyxpy
uv pip remove electrickiwi-api
uv pip remove elevenlabs
uv pip remove elgato
uv pip remove eliqonline
uv pip remove elkm1-lib
uv pip remove elkoep-aio-mqtt
uv pip remove elmax-api
uv pip remove elvia
uv pip remove emoji
uv pip remove emulated-roku
uv pip remove energyflip-client
uv pip remove energyid-webhooks
uv pip remove energyzero
uv pip remove enocean
uv pip remove enturclient
uv pip remove env-canada
uv pip remove ephem
uv pip remove epicstore-api
uv pip remove epion
uv pip remove epson-projector
uv pip remove eq3btsmart
uv pip remove esphome-dashboard-api
uv pip remove essent-dynamic-pricing
uv pip remove eternalegypt
uv pip remove eufylife-ble-client
uv pip remove # evdev
uv pip remove evohome-async
uv pip remove evolutionhttp
uv pip remove faadelays
uv pip remove fastdotcom
uv pip remove feedparser
uv pip remove file-read-backwards
uv pip remove fing_agent_api
uv pip remove fints
uv pip remove fitbit-web-api
uv pip remove fitbit
uv pip remove fivem-api
uv pip remove fixerio
uv pip remove fjaraskupan
uv pip remove flexit_bacnet
uv pip remove flipr-api
uv pip remove flux-led
uv pip remove fnv-hash-fast
uv pip remove foobot_async
uv pip remove forecast-solar
uv pip remove fortiosapi
uv pip remove freebox-api
uv pip remove freesms
uv pip remove fressnapftracker
uv pip remove fritzconnection[qr]
uv pip remove fyta_cli
uv pip remove gTTS
uv pip remove gardena-bluetooth
uv pip remove gassist-text
uv pip remove gcal-sync
uv pip remove genie-partner-sdk
uv pip remove geniushub-client
uv pip remove geocachingapi
uv pip remove geopy
uv pip remove georss-generic-client
uv pip remove georss-ign-sismologia-client
uv pip remove georss-qld-bushfire-alert-client
uv pip remove getmac
uv pip remove gios
uv pip remove gitterpy
uv pip remove glances-api
uv pip remove go2rtc-client
uv pip remove goalzero
uv pip remove goodwe
uv pip remove google-api-python-client
uv pip remove google-cloud-pubsub
uv pip remove google-cloud-speech
uv pip remove google-cloud-texttospeech
uv pip remove google-genai
uv pip remove google-maps-routing
uv pip remove google-nest-sdm
uv pip remove google-photos-library-api
uv pip remove google_air_quality_api
uv pip remove goslide-api
uv pip remove gotailwind
uv pip remove govee-ble
uv pip remove govee-local-api
uv pip remove gpiozero
uv pip remove gps3
uv pip remove greeclimate
uv pip remove greeneye_monitor
uv pip remove greenwavereality
uv pip remove gridnet
uv pip remove growattServer
uv pip remove gspread
uv pip remove guppy3
uv pip remove h2
uv pip remove ha-ffmpeg
uv pip remove ha-iotawattpy
uv pip remove ha-philipsjs
uv pip remove ha-silabs-firmware-client
uv pip remove habiticalib
uv pip remove habluetooth
uv pip remove hanna-cloud
uv pip remove hass-nabucasa
uv pip remove hass-splunk
uv pip remove hassil
uv pip remove hdate[astral]
uv pip remove heatmiserV3
uv pip remove here-routing
uv pip remove here-transit
uv pip remove hikvision
uv pip remove hkavr
uv pip remove hko
uv pip remove hlk-sw16
uv pip remove hole
uv pip remove holidays
uv pip remove home-assistant-frontend
uv pip remove home-assistant-intents
uv pip remove homelink-integration-api
uv pip remove homematicip
uv pip remove horimote
uv pip remove httplib2
uv pip remove huawei-lte-api
uv pip remove huum
uv pip remove hyperion-py
uv pip remove iammeter
uv pip remove iaqualink
uv pip remove ibeacon-ble
uv pip remove ical
uv pip remove icalendar
uv pip remove icmplib
uv pip remove idasen-ha
uv pip remove ifaddr
uv pip remove iglo
uv pip remove igloohome-api
uv pip remove ihcsdk
uv pip remove imeon_inverter_api
uv pip remove imgw_pib
uv pip remove incomfort-client
uv pip remove influxdb-client
uv pip remove influxdb
uv pip remove inkbird-ble
uv pip remove insteon-frontend-home-assistant
uv pip remove intellifire4py
uv pip remove iometer
uv pip remove iottycloud
uv pip remove iperf3
uv pip remove irm-kmi-api
uv pip remove isal
uv pip remove ismartgate
uv pip remove israel-rail-api
uv pip remove jaraco.abode
uv pip remove jellyfin-apiclient-python
uv pip remove jsonpath
uv pip remove justnimbus
uv pip remove kaiterra-async-client
uv pip remove keba-kecontact
uv pip remove kegtron-ble
uv pip remove kiwiki-client
uv pip remove knocki
uv pip remove knx-frontend
uv pip remove konnected
uv pip remove krakenex
uv pip remove lacrosse-view
uv pip remove lakeside
uv pip remove laundrify-aio
uv pip remove lcn-frontend
uv pip remove ld2410-ble
uv pip remove leaone-ble
uv pip remove led-ble
uv pip remove lektricowifi
uv pip remove letpot
uv pip remove libpyfoscamcgi
uv pip remove libpyvivotek
uv pip remove librehardwaremonitor-api
uv pip remove librouteros
uv pip remove libsoundtouch
uv pip remove lightify
uv pip remove lightwave
uv pip remove limitlessled
uv pip remove linode-api
uv pip remove livisi
uv pip remove locationsharinglib
uv pip remove london-tube-status
uv pip remove loqedAPI
uv pip remove luftdaten
uv pip remove lunatone-rest-api-client
uv pip remove lupupy
uv pip remove lw12
uv pip remove lxml
uv pip remove matrix-nio
uv pip remove maxcube-api
uv pip remove mbddns
uv pip remove mcp
uv pip remove mcstatus
uv pip remove meater-python
uv pip remove medcom-ble
uv pip remove melnor-bluetooth
uv pip remove messagebird
uv pip remove meteo-lt-pkg
uv pip remove meteoalertapi
uv pip remove meteofrance-api
uv pip remove mficlient
uv pip remove micloud
uv pip remove microBeesPy
uv pip remove mill-local
uv pip remove millheater
uv pip remove minio
uv pip remove moat-ble
uv pip remove moehlenhoff-alpha2
uv pip remove momonga
uv pip remove monzopy
uv pip remove mopeka-iot-ble
uv pip remove motionblinds
uv pip remove motionblindsble
uv pip remove motioneye-client
uv pip remove mozart-api
uv pip remove mullvad-api
uv pip remove music-assistant-client
uv pip remove mutagen
uv pip remove mutesync
uv pip remove mvg
uv pip remove mypermobil
uv pip remove myuplink
uv pip remove nad-receiver
uv pip remove ndms2-client
uv pip remove nessclient
uv pip remove netdata
uv pip remove netmap
uv pip remove nettigo-air-monitor
uv pip remove neurio
uv pip remove nexia
uv pip remove nextcloudmonitor
uv pip remove nextcord
uv pip remove nextdns
uv pip remove nhc
uv pip remove nibe
uv pip remove nice-go
uv pip remove niluclient
uv pip remove noaa-coops
uv pip remove notifications-android-tv
uv pip remove notify-events
uv pip remove nsapi
uv pip remove nsw-fuel-api-client
uv pip remove nuheat
uv pip remove numato-gpio
uv pip remove numpy
uv pip remove nyt_games
uv pip remove oasatelematics
uv pip remove oauth2client
uv pip remove objgraph
uv pip remove odp-amsterdam
uv pip remove oemthermostat
uv pip remove ohme
uv pip remove ollama
uv pip remove omnilogic
uv pip remove ondilo
uv pip remove onedrive-personal-sdk
uv pip remove onvif-zeep-async
uv pip remove open-garage
uv pip remove open-meteo
uv pip remove openai
uv pip remove openerz-api
uv pip remove openevsewifi
uv pip remove openhomedevice
uv pip remove openrgb-python
uv pip remove opensensemap-api
uv pip remove openwebifpy
uv pip remove openwrt-luci-rpc
uv pip remove openwrt-ubus-rpc
uv pip remove opower
uv pip remove oralb-ble
uv pip remove oru
uv pip remove orvibo
uv pip remove ourgroceries
uv pip remove ovoenergy
uv pip remove p1monitor
uv pip remove paho-mqtt
uv pip remove panacotta
uv pip remove panasonic-viera
uv pip remove pdunehd
uv pip remove peblar
uv pip remove peco
uv pip remove pencompy
uv pip remove pescea
uv pip remove pexpect
uv pip remove phone-modem
uv pip remove pigpio
uv pip remove pilight
uv pip remove plexauth
uv pip remove plexwebsocket
uv pip remove plugwise
uv pip remove pmsensor
uv pip remove poolsense
uv pip remove powerfox
uv pip remove praw
uv pip remove prayer-times-calculator-offline
uv pip remove proliphix
uv pip remove prometheus-client
uv pip remove prowlpy
uv pip remove proxmoxer
uv pip remove psutil-home-assistant
uv pip remove psutil
uv pip remove pulsectl
uv pip remove pushbullet.py
uv pip remove pushover_complete
uv pip remove pvo
uv pip remove py-aosmith
uv pip remove py-canary
uv pip remove py-cpuinfo
uv pip remove py-dactyl
uv pip remove py-dormakaba-dkey
uv pip remove py-improv-ble-client
uv pip remove py-madvr2
uv pip remove py-melissa-climate
uv pip remove py-nextbusnext
uv pip remove py-nightscout
uv pip remove py-schluter
uv pip remove py-sucks
uv pip remove py-synologydsm-api
uv pip remove pyAtome
uv pip remove pyCEC
uv pip remove pyControl4
uv pip remove pyDuotecno
uv pip remove pyElectra
uv pip remove pyEmby
uv pip remove pyHik
uv pip remove pyHomee
uv pip remove pyRFXtrx
uv pip remove pySDCP
uv pip remove pyTibber
uv pip remove pyW215
uv pip remove pyW800rf32
uv pip remove py_ccm15
uv pip remove pyads
uv pip remove pyaehw4a1
uv pip remove pyaftership
uv pip remove pyairnow
uv pip remove pyairobotrest
uv pip remove pyairvisual
uv pip remove pyanglianwater
uv pip remove pyaprilaire
uv pip remove pyatag
uv pip remove pyatmo
uv pip remove pyatv
uv pip remove pyaussiebb
uv pip remove pybalboa
uv pip remove pybbox
uv pip remove pyblackbird
uv pip remove pyblu
uv pip remove pybotvac
uv pip remove pybravia
uv pip remove pycarwings2
uv pip remove pycfdns
uv pip remove pychannels
uv pip remove pycketcasts
uv pip remove pycmus
uv pip remove pycomfoconnect
uv pip remove pycoolmasternet-async
uv pip remove pycountry
uv pip remove pycsspeechtts
uv pip remove pycync
uv pip remove pydaikin
uv pip remove pydanfossair
uv pip remove pydeako
uv pip remove pydeconz
uv pip remove pydelijn
uv pip remove pydexcom
uv pip remove pydiscovergy
uv pip remove pydoods
uv pip remove pydrawise
uv pip remove pydroid-ipcam
uv pip remove pydroplet
uv pip remove pyebox
uv pip remove pyecoforest
uv pip remove pyeconet
uv pip remove pyecotrend-ista
uv pip remove pyedimax
uv pip remove pyefergy
uv pip remove pyegps
uv pip remove pyemoncms
uv pip remove pyenphase
uv pip remove pyenvisalink
uv pip remove pyephember2
uv pip remove pyeverlights
uv pip remove pyevilgenius
uv pip remove pyezvizapi
uv pip remove pyfibaro
uv pip remove pyfido
uv pip remove pyfirefly
uv pip remove pyfireservicerota
uv pip remove pyflic
uv pip remove pyfnip
uv pip remove pyforked-daapd
uv pip remove pyfreedompro
uv pip remove pyfritzhome
uv pip remove pyfttt
uv pip remove pygatt[GATTTOOL]
uv pip remove pygtfs
uv pip remove pygti
uv pip remove pyhaversion
uv pip remove pyheos
uv pip remove pyhive-integration
uv pip remove pyhomematic
uv pip remove pyhomeworks
uv pip remove pyialarm
uv pip remove pyicloud
uv pip remove pyinsteon
uv pip remove pyintesishome
uv pip remove pyipma
uv pip remove pyipp
uv pip remove pyiqvia
uv pip remove pyirishrail
uv pip remove pyiskra
uv pip remove pyiss
uv pip remove pyisy
uv pip remove pyitachip2ir
uv pip remove pyituran
uv pip remove pyjvcprojector
uv pip remove pykaleidescape
uv pip remove pykira
uv pip remove pykmtronic
uv pip remove pykodi
uv pip remove pykoplenti
uv pip remove pykrakenapi
uv pip remove pykulersky
uv pip remove pykwb
uv pip remove pylacrosse
uv pip remove pylamarzocco
uv pip remove pylast
uv pip remove pylaunches
uv pip remove pylgnetcast
uv pip remove pylibrespot-java
uv pip remove pylitejet
uv pip remove pylitterbot
uv pip remove pylutron-caseta
uv pip remove pylutron
uv pip remove pymailgunner
uv pip remove pymata-express
uv pip remove pymediaroom
uv pip remove pymeteoclimatic
uv pip remove pymicro-vad
uv pip remove pymiele
uv pip remove pymitv
uv pip remove pymochad
uv pip remove pymodbus
uv pip remove pymonoprice
uv pip remove pymsteams
uv pip remove pymysensors
uv pip remove pynecil
uv pip remove pynetgear
uv pip remove pynetio
uv pip remove pynina
uv pip remove pynintendoparental
uv pip remove pynobo
uv pip remove pynordpool
uv pip remove pynuki
uv pip remove pynws[retry]
uv pip remove pynx584
uv pip remove pynzbgetapi
uv pip remove pyobihai
uv pip remove pyoctoprintapi
uv pip remove pyombi
uv pip remove pyopenuv
uv pip remove pyopenweathermap
uv pip remove pyopnsense
uv pip remove pyoppleio-legacy
uv pip remove pyosoenergyapi
uv pip remove pyotgw
uv pip remove pyotp
uv pip remove pyoverkiz
uv pip remove pypalazzetti
uv pip remove pypaperless
uv pip remove pypca
uv pip remove pypck
uv pip remove pypglab
uv pip remove pypjlink2
uv pip remove pyplaato
uv pip remove pypoint
uv pip remove pyportainer
uv pip remove pyprobeplus
uv pip remove pyprof2calltree
uv pip remove pyprosegur
uv pip remove pyprusalink
uv pip remove pyps4-2ndscreen
uv pip remove pyqvrpro
uv pip remove pyqwikswitch
uv pip remove pyrail
uv pip remove pyrainbird
uv pip remove pyrate-limiter
uv pip remove pyrecswitch
uv pip remove pyrepetierng
uv pip remove pyrisco
uv pip remove pyrituals
uv pip remove pyroute2
uv pip remove pyrympro
uv pip remove pysabnzbd
uv pip remove pysaj
uv pip remove pysaunum
uv pip remove pyschlage
uv pip remove pysensibo
uv pip remove pyserial-asyncio-fast
uv pip remove pyserial
uv pip remove pysesame2
uv pip remove pyseventeentrack
uv pip remove pysiaalarm
uv pip remove pysignalclirestapi
uv pip remove pyskyqhub
uv pip remove pysma
uv pip remove pysmappee
uv pip remove pysmarlaapi
uv pip remove pysmartthings
uv pip remove pysmarty2
uv pip remove pysmhi
uv pip remove pysml
uv pip remove pysmlight
uv pip remove pysnmp
uv pip remove pysnooz
uv pip remove pysoma
uv pip remove pyspcwebgw
uv pip remove pyspeex-noise
uv pip remove pysqueezebox
uv pip remove pystiebeleltron
uv pip remove pysuezV2
uv pip remove pyswitchbee
uv pip remove pytautulli
uv pip remove pythinkingcleaner
uv pip remove python-MotionMount
uv pip remove python-awair
uv pip remove python-blockchain-api
uv pip remove python-bsblan
uv pip remove python-citybikes
uv pip remove python-clementine-remote
uv pip remove python-digitalocean
uv pip remove python-ecobee-api
uv pip remove python-etherscan-api
uv pip remove python-family-hub-local
uv pip remove python-fullykiosk
uv pip remove python-gc100
uv pip remove python-gitlab
uv pip remove python-google-drive-api
uv pip remove python-google-weather-api
uv pip remove python-homeassistant-analytics
uv pip remove python-homewizard-energy
uv pip remove python-hpilo
uv pip remove python-izone
uv pip remove python-join-api
uv pip remove python-kasa[speedups]
uv pip remove python-linkplay
uv pip remove python-matter-server
uv pip remove python-melcloud
uv pip remove python-miio
uv pip remove python-mpd2
uv pip remove python-mystrom
uv pip remove python-open-router
uv pip remove python-opendata-transport
uv pip remove python-opensky
uv pip remove python-otbr-api
uv pip remove python-overseerr
uv pip remove python-picnic-api2
uv pip remove python-pooldose
uv pip remove python-rabbitair
uv pip remove python-ripple-api
uv pip remove python-roborock
uv pip remove python-smarttub
uv pip remove python-snoo
uv pip remove python-songpal
uv pip remove python-tado
uv pip remove python-technove
uv pip remove python-telegram-bot[socks]
uv pip remove python-vlc
uv pip remove python-xbox
uv pip remove pythonegardia
uv pip remove pythonkuma
uv pip remove pytile
uv pip remove pytomorrowio
uv pip remove pytouchline_extended
uv pip remove pytouchlinesl
uv pip remove pytraccar
uv pip remove pytradfri[async]
uv pip remove pytrafikverket
uv pip remove pytrydan
uv pip remove pyuptimerobot
uv pip remove pyvera
uv pip remove pyversasense
uv pip remove pyvesync
uv pip remove pyvizio
uv pip remove pyvlx
uv pip remove pyvolumio
uv pip remove pywaze
uv pip remove pyweatherflowudp
uv pip remove pywebpush
uv pip remove pywemo
uv pip remove pywilight
uv pip remove pywizlight
uv pip remove pywmspro
uv pip remove pyws66i
uv pip remove pyxeoma
uv pip remove pyyardian
uv pip remove pyzbar
uv pip remove pyzerproc
uv pip remove qbittorrent-api
uv pip remove qbusmqttapi
uv pip remove qingping-ble
uv pip remove qnapstats
uv pip remove quantum-gateway
uv pip remove radios
uv pip remove radiotherm
uv pip remove raincloudy
uv pip remove rapt-ble
uv pip remove raspyrfm-client
uv pip remove refoss-ha
uv pip remove regenmaschine
uv pip remove renault-api
uv pip remove renson-endura-delta
uv pip remove reolink-aio
uv pip remove rfk101py
uv pip remove rflink
uv pip remove ring-doorbell
uv pip remove ritassist
uv pip remove rjpl
uv pip remove rocketchat-API
uv pip remove rokuecp
uv pip remove romy
uv pip remove roombapy
uv pip remove roonapi
uv pip remove rova
uv pip remove rpi-bad-power
uv pip remove russound
uv pip remove ruuvitag-ble
uv pip remove rxv
uv pip remove samsungctl[websocket]
uv pip remove samsungtvws[async,encrypted]
uv pip remove sanix
uv pip remove satel-integra
uv pip remove screenlogicpy
uv pip remove scsgate
uv pip remove securetar
uv pip remove sendgrid
uv pip remove sense-energy
uv pip remove sensirion-ble
uv pip remove sensorpro-ble
uv pip remove sensorpush-api
uv pip remove sensorpush-ble
uv pip remove sensorpush-ha
uv pip remove sensoterra
uv pip remove sentence-stream
uv pip remove sentry-sdk
uv pip remove sfrbox-api
uv pip remove sharkiq
uv pip remove sharp_aquos_rc
uv pip remove shodan
uv pip remove simplefin4py
uv pip remove simplehound
uv pip remove simplepush
uv pip remove simplisafe-python
uv pip remove sisyphus-control
uv pip remove skyboxremote
uv pip remove slack_sdk
uv pip remove slixmpp
uv pip remove smart-meter-texas
uv pip remove snapcast
uv pip remove soco
uv pip remove solaredge-local
uv pip remove solaredge-web
uv pip remove solarlog_cli
uv pip remove solax
uv pip remove somfy-mylink-synergy
uv pip remove sonos-websocket
uv pip remove speak2mary
uv pip remove speedtest-cli
uv pip remove spotifyaio
uv pip remove sqlparse
uv pip remove srpenergy
uv pip remove starline
uv pip remove starlingbank
uv pip remove starlink-grpc-core
uv pip remove statsd
uv pip remove steamodd
uv pip remove stookwijzer
uv pip remove streamlabswater
uv pip remove subarulink
uv pip remove surepy
uv pip remove swisshydrodata
uv pip remove switchbot-api
uv pip remove synology-srm
uv pip remove systembridgeconnector
uv pip remove tailscale
uv pip remove tank-utility
uv pip remove tapsaff
uv pip remove tellcore-net
uv pip remove tellcore-py
uv pip remove tellduslive
uv pip remove temescal
uv pip remove temperusb
uv pip remove tesla-fleet-api
uv pip remove tesla-powerwall
uv pip remove tesla-wall-connector
uv pip remove teslemetry-stream
uv pip remove tessie-api
uv pip remove thermobeacon-ble
uv pip remove thermopro-ble
uv pip remove thingspeak
uv pip remove thinqconnect
uv pip remove tikteck
uv pip remove tilt-ble
uv pip remove tilt-pi
uv pip remove tmb
uv pip remove todoist-api-python
uv pip remove togrill-bluetooth
uv pip remove tololib
uv pip remove toonapi
uv pip remove total-connect-client
uv pip remove tp-connected
uv pip remove tplink-omada-client
uv pip remove transmission-rpc
uv pip remove triggercmd
uv pip remove ttls
uv pip remove ttn_client
uv pip remove tuya-device-sharing-sdk
uv pip remove twentemilieu
uv pip remove twilio
uv pip remove twitchAPI
uv pip remove typedmonarchmoney
uv pip remove uasiren
uv pip remove uiprotect
uv pip remove ultraheat-api
uv pip remove unifi-discovery
uv pip remove unifi_ap
uv pip remove unifiled
uv pip remove universal-silabs-flasher
uv pip remove upb-lib
uv pip remove upcloud-api
uv pip remove url-normalize
uv pip remove uvcclient
uv pip remove vacuum-map-parser-roborock
uv pip remove vallox-websocket-api
uv pip remove vegehub
uv pip remove vehicle
uv pip remove velbus-aio
uv pip remove venstarcolortouch
uv pip remove victron-ble-ha-parser
uv pip remove victron-vrm
uv pip remove vilfo-api-client
uv pip remove vobject
uv pip remove voip-utils
uv pip remove volkszaehler
uv pip remove volvocarsapi
uv pip remove vsure
uv pip remove vtjp
uv pip remove wakeonlan
uv pip remove wallbox
uv pip remove watchdog
uv pip remove waterfurnace
uv pip remove watergate-local-api
uv pip remove weatherflow4py
uv pip remove webexpythonsdk
uv pip remove webio-api
uv pip remove webmin-xmlrpc
uv pip remove weheat
uv pip remove whirlpool-sixth-sense
uv pip remove whois
uv pip remove wiffi
uv pip remove wirelesstagpy
uv pip remove wled
uv pip remove wolf-comm
uv pip remove wsdot
uv pip remove wyoming
uv pip remove xiaomi-ble
uv pip remove xknx
uv pip remove xknxproject
uv pip remove xmltodict
uv pip remove xs1-api-client
uv pip remove yalesmartalarmclient
uv pip remove yalexs-ble
uv pip remove yalexs
uv pip remove yeelight
uv pip remove yeelightsunflower
uv pip remove yolink-api
uv pip remove youless-api
uv pip remove youtubeaio
uv pip remove yt-dlp[default]
uv pip remove zabbix-utils
uv pip remove zamg
uv pip remove zcc-helper
uv pip remove zeroconf
uv pip remove zeversolar
uv pip remove zha
uv pip remove zhong-hong-hvac
uv pip remove ziggo-mediabox-xl
uv pip remove zm-py
uv pip remove zwave-js-server-python
uv pip remove zwave-me-ws
EOF

# Stage 2: Create the final image with metadata
FROM base
LABEL maintainer="Timandes"
LABEL description="Slim version of Home Assistant for ARM64 architecture"
LABEL version="${HA_VERSION}"